### ISSUE TITLE
Calls to Clipper.getUserSessionId() occasionally are not returning the correct value

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/WebClipper#103]
We have seen cases where the first two augmentation calls are sending up a session ID that doesn't correlate with the one being sent to our logging endpoint.

**Comment by mttwc** [comment]
Clipper.getUserSessionId() is returning the right thing. We were setting the session id in the request as correlation id. I have a PR out that properly sets the correlation id and session id on early requests (Augmentation, FullPage) with their corresponding values.
