### ISSUE TITLE
Clipper No-ops if user has Mozilla PDF Reader installed

### ISSUE THREAD

**Issue by VishaalK** [OneNoteDev/WebClipper#112]
This PDF Reader (not the one that says Mozilla PDF Reader): https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

**Comment by mttwc** [comment]
"Cannot access a chrome-extension:// URL of different extension"

**Comment by mttwc** [comment]
Currently working to get strings for a more suitable error message. We can even use the competing extension's id to link the user to the store since we can't get the name of the extension directly. E.g.,
`https://chrome.google.com/webstore/detail/<id>`
