### ISSUE TITLE
Split up and add UTs for SaveToOneNote.ts

### ISSUE THREAD

**Issue by mttwc** [OneNoteDev/WebClipper#124]
This file is getting pretty big as we made more flexibility to each of our clipping modes. We should look to split this apart to make things easier to validate and understand.

**Comment by VishaalK** [comment]
We should also look at `startClip()` within `clipper.tsx`

**Comment by mttwc** [comment]
I'm making this high-priority. We hit an issue in prod where timeouts won't hit the new error panel (https://github.com/OneNoteDev/WebClipper/pull/185). I think this could have been entirely avoided if we had UTs for the methods in SaveToOneNote.ts. We should split this up as soon as we can and ensure that we have test coverage.
