### ISSUE TITLE
A user reported that the div we insert on pageNav can cause some problems with other add-ons

### ISSUE THREAD

**Issue by VishaalK** [OneNoteDev/WebClipper#166]
We insert a div on pageNav in order to detect if the Clipper is already installed to make some experiences smoother.

![image](https://cloud.githubusercontent.com/assets/3259870/19866923/5ff2d6f4-9f5f-11e6-9d23-54c48eaaf1ad.png)

A user reported it might cause issues so we are going to investigate so we don't break other extensions

**Comment by iconix** [comment]
Adding the permalink to this review: https://addons.mozilla.org/en-US/firefox/addon/onenote-clipper/reviews/824897/

## 

Also, we should be inserting the div in an way that keeps the HTML valid -- so inside the body tag. This could be this user's concern.
