### ISSUE TITLE
Users reported that they are made to sign in every time

### ISSUE THREAD

**Issue by iconix** [OneNoteDev/WebClipper#175]
See the _Ratings Prompt Feature Data_ page for links to the particular user feedback.

**Comment by leakymemory** [comment]
I'm going to close this as there isn't a lot actionable at this point. We don't believe this is a wide-spread issue, and without either a repro case or someone who is hitting this that we can talk to.

I should note that there are a couple semi-legitimate ways in which this can happen.  One that has come up recently is people who have the "clear all my settings when I close" feature enabled on their browser.  I would guess though, that those people are used to signing in every time.

If this gets reported again, or we find a good way to reproduce it then we'll re-open.
