### ISSUE TITLE
Inject script breaks when invoked on https://mochajs.org/

### ISSUE THREAD

**Issue by ghost** [OneNoteDev/WebClipper#209]
Firefox console report:
 
firefoxInject.js:12087 -> **module is not defines**

This is the row:
`(function(f,h){"object"===typeof exports?module.exports=h():"function"===typeof define&&define.amd?define(h):f.IPv6=h(f)})(this,function(f){var h=f&&f.IPv6;return{best:function(g){g=g.toLowerCase().split(":");var n=g.length,b=8;""===g[0]&&""===g[1]&&""===g[2]?(g.shift(),g.shift()):""===g[0]&&""===g[1]?g.shift():""===g[n-1]&&""===g[n-2]&&g.pop();n=g.length;-1!==g[n-1].indexOf(".")&&(b=7);var k;for(k=0;k<n&&""!==g[k];k++);if(k<b)for(g.splice(k,1,"0000");g.length<b;)g.splice(k,0,"0000");for(k=0;k<b;k++){for(var n=`

Details:
Firefox version 50.0
Also tried on Firefox Developer edition (ver 51.0a2): same error.

**Comment by mttwc** [comment]
Hi Rob! Thanks for bringing this up! We're looking into this now.

We're testing the freshly installed extension from the Mozilla addons site on Firefox 50 and it's working fine for us. May we know what sites you are trying to clip? We noticed that the addons site itself would not allow us to invoke the clipper on their page.

**Comment by ghost** [comment]
Hi @mttwc you're right!!
The probematic site is https://mochajs.org
In the other sites all works.
Thanks 👍

**Comment by larsendaniel** [comment]
I get the same on that site with Chrome

**Comment by mttwc** [comment]
Thanks for getting back to us! I can repro the issue on that site as well. I've updated the issue title to reflect this. I'll look into it, but on first sight it looks like the site's JS clashes in some way with our inject script. This is happening in Chrome as well.

**Comment by mttwc** [comment]
After some digging, it's got something to do with requirejs? I'm not fully sure, but I'll play around.
Related: https://github.com/medialize/URI.js/issues/118

**Comment by mttwc** [comment]
if (typeof exports === 'object') is incorrectly returning true. 'exports' in this case is actually an HTML h3 element! It's probably being set incorrectly somewhere, so the wrong part of the if-else is being executed.

**Comment by mttwc** [comment]
I verified that hardcoding that bit of code to false fixes the issue. Trying to think of a proper fix.

**Comment by mttwc** [comment]
I've submitted a PR to the URI.js project that will fix this.

Tracking here
Issue: https://github.com/medialize/URI.js/issues/318
PR: https://github.com/medialize/URI.js/pull/319

Hopefully we'll see it merged soon :)
