### ISSUE TITLE
getIndicesOfVisiblePages infinite loops/crashes the Clipper if you click another mode button while it is trying to load some images

### ISSUE THREAD

**Issue by VishaalK** [OneNoteDev/WebClipper#211]
1. Open a Clipper in a PDF mode
2. Scroll so that there are blank images
3. While the images are loading, click on "Region Mode"

**Result**: Clipper hangs

**Comment by mttwc** [comment]
getIndicesOfVisiblePages is the culprit that's causing it to crash. Digging in and trying to figure out why now.
