### ISSUE TITLE
Firefox, OSX12: Region selection is off

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/WebClipper#257]
It looks like in Firefox, region selection is off and what the user selects is definitely not what they're getting.

Verified with most recent version of Firefox (50.0.2)

**Comment by mttwc** [comment]
Marking this as OSX12 as this doesn't seem to be an issue on Windows or OSX 11 El Capitan

**Comment by VishaalK** [comment]
Bug potentially tracking the same issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1278507

The gist is that Firefox may not be correctly taking into account the devicePixelRatio when returning the bounds of the image. I recall @larsendaniel did some work on getting it to work with Retina screens, and got almost all the way but figured out it wasn't possible at the time.
