### ISSUE TITLE
Recipes labeled as Products, Products labeled as Articles

### ISSUE THREAD

**Issue by mttwc** [OneNoteDev/WebClipper#276]
Repro by invoking the clipper on each of these links:

http://www.seriouseats.com/recipes/2016/10/pressure-cooker-tomato-sauce.html

https://www.amazon.com/Logitech-Harmony-Ultimate-Customizable-Cabinet/dp/B00BQ5RY1G/ref=gbph_img_m-3_f3ee_77320560?smid=ATVPDKIKX0DER&pf_rd_p=f8221e3c-958b-4601-81d4-a545a755f3ee&pf_rd_s=merchandised-search-3&pf_rd_t=101&pf_rd_i=11516390011&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=2YRZ878V00MVRHG9GPHM

**Comment by VishaalK** [comment]
The AugmentationApi added a new ContentModel, and in our code we had a dependency on the numeric values of the ENUMs. Augmentation has decided to change this into a string to break this dependency.
