### ISSUE TITLE
Upgrade to popper.js v1 when it comes out of beta

### ISSUE THREAD

**Issue by mttwc** [OneNoteDev/WebClipper#284]
Popper.js has a v1 beta out, and we should expect it to release v1 soon. We should keep a close eye on it and validate/upgrade when we're able to.

**Comment by FezVrasta** [comment]
Hi guys, I released beta.3, it would be awesome to get some feedbacks from you if you have some time to dedicate. If no bugs are raised in the next few days I'm going to promote this beta to RC.

**Comment by mttwc** [comment]
Hey @FezVrasta, I'll check it out :)

**Comment by mttwc** [comment]
@FezVrasta, it looks like the Popper constructor's popper param has changed to only accept an HTMLElement rather than a configuration object. We're currently instantiating the popper using the config object. Are you intending on continuing to support this?

We use popper here if you're interested in seeing how we instantiate it: https://github.com/OneNoteDev/WebClipper/blob/master/src/scripts/clipperUI/components/popover.tsx

**Comment by FezVrasta** [comment]
nope, it was really out of scope and I wanted to keep the core specialized.

You may use the Tooltip.js side-library that is shipped with v1 maybe?

Otherwise, it's fairly easy to simply create the node before the Popper initialization.

**Comment by FezVrasta** [comment]
I was thinking that you could re-introduce the old feature with a custom modifier (basically, I copy-pasted the functions from v0):
https://gist.github.com/FezVrasta/075d228ffb855688c75a69c6d1d6afce

Looking at the amount of code needed for this feature I hope you will understand why I dropped it from the core.

**Comment by FezVrasta** [comment]
@mttwc I plan to release v1 tomorrow or the day after, so I wanted to make sure everything looks good to you before.

Do I have your blessing? 🙂

**Comment by mttwc** [comment]
@FezVrasta I'll be happy to take a look at v1 and Tooltip.js. Thanks for following up on this!

**Comment by mttwc** [comment]
I have v1 beta 4 working on a local branch (replacing our config object with manually constructing the tooltip with divs). It looks good to me! Is there anything else in particular you'd like me to look at?

**Comment by FezVrasta** [comment]
nope, just wanted to be sure that everything was good to you use case. thanks

**Comment by mttwc** [comment]
Thank you :)

**Comment by mttwc** [comment]
Congraulations on shipping v1 @FezVrasta! I'm working to integrate the changes over now on this end. Just running into a weird issue in our UTs.
