### ISSUE TITLE
Recipes sometimes duplicating ingredients

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/WebClipper#285]
Customer reported issue.  It looks like we're not parsing the ingredients right and ending up duplicating things.

Here's an example of a page that does this:
[http://www.epicurious.com/recipes/food/views/bread-pudding-with-spiced-rum-sauce-105700](http://www.epicurious.com/recipes/food/views/bread-pudding-with-spiced-rum-sauce-105700)

```When I clip an articale or recipe from the web using onenote web clipper I often get double entries of  words.  Below is an example:
INGREDIENT
3.5 cups#3 1/2 cups whole milk 1/2 cups whole milk
2 cups#2 cups sugar
1.5 cups#1 1/2 cups whipping cream 1/2 cups whipping cream
1 teaspoon#1 teaspoon vanilla extract vanilla extract
1 loaf#1 1-pound loaf cinnamon challah or cinnamon-swirl bread, cut into 1-inch cubes 1-pound loaf cinnamon challah or cinnamon-swirl bread, cut into 1-inch cubes
1 cup#1 cup golden raisins golden raisins```

**Comment by leakymemory** [comment]
Here's the link to the forum post about this:
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_onenote-mso_win10/double-entries-from-onenote-clipper/942e2646-80c6-4657-9196-14f5189eff4a

**Comment by mttwc** [comment]
Also repro'd on another epicurious recipe: http://www.epicurious.com/recipes/food/views/red-wine-braised-shortribs-367736

Looks like everything to left of the '#' signifies the quantity of the ingredient? It doesn't look like the text is coming from the page itself.

**Comment by leakymemory** [comment]
Ok, we have identified where this is failing and are following up now with the owner of the service.  No ETA on the fix yet, but progress at least.

**Comment by leakymemory** [comment]
The fix for this has been deployed and the ingredients are getting listed as expected again.
