### ISSUE TITLE
Unable to install the extension on Firefox ESR 45.3.0

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/WebClipper#36]
It looks like the clipper is not able to install on Firefox ESR builds 45.3+.  I dug around the documentation and couldn't find anything saying that web extension support isn't yet available, and according to [this ](https://www.mozilla.org/en-US/firefox/organizations/faq/) page, 45.3 is the equivalent to 48 on the standard track, so I think it _should_ work.

Current working theory: We set the minimum Firefox version to 48 and because the ESR builds are on a different versioning track, it's blocking the extension even though technically it should work fine.

**Comment by VishaalK** [comment]
Firefox ESR 45.3 does not have supported WebExtensions or for Add-on Signing so our v3 will not work on it. Firefox 52 is slated for 3/7/2017 😭, which will be the next ESR update.

**Comment by leakymemory** [comment]
Yep, sad, but unfortunately not a lot we can do about it.  I'm closing this issue and have communicated back to the customer this information.
