### ISSUE TITLE
The images that are rendered from a PDF are very low quality

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/WebClipper#369]
It looks like we are losing a lot of the quality when we convert a PDF to an image.  I don't think it was this bad when we first implemented the feature, but certainly it is noticeable now.  Here is a good example of a PDF that looks especially bad when clipped:

http://onlinelibrary.wiley.com/doi/10.1111/j.1651-2227.2006.00180.x/epdf

Note that you'll need to download the PDF locally and then load it from the file:// URL (since we don't detect it as a PDF from the original URL).

**Comment by leakymemory** [comment]
I have a local fix which seems to address the problem.  It seems that we need to bump up the viewport scale.  I'm digging it what other impacts this will have (guessing larger file size).

**Comment by ChenglongWang** [comment]
Thank you very much for fix the quality problem, hope it can be released soon.  But I'm still confused that not only pdf, but all web pages clipping are converted to low quality image in Onenote, or it may be my setting problem? 

I've captured a part of image in my Onenote.
![image](https://cloud.githubusercontent.com/assets/4251375/26141053/e4f7809c-3b14-11e7-8caa-bf8530f674d1.png)

**Comment by leakymemory** [comment]
This fix was specific to the PDF clipping.  I'll open a separate issue where we can look at the more general image quality overall.  As you might expect, there is always a balance between high quality vs.  download/upload size (i.e. size of image).  We thought we had this in a good place, but certainly we are willing to look where we can improve things.  I've opened issue #373 to help track the issue.

Thanks!

**Comment by leakymemory** [comment]
Note that this was pushed out to the Chrome store today as version 3.7.4.
