### ISSUE TITLE
Unify mockStorage objects in tests

### ISSUE THREAD

**Issue by iconix** [OneNoteDev/WebClipper#41]
PR https://github.com/OneNoteDev/WebClipper/pull/22 comment from @VishaalK:

> We have 3-ish versions of `mockStorage` out there. I see one in `tooltipHelper_tests.ts`, another in `sectionPicker_tests.ts`. Can you add a low pri PBI to unify these?

**Comment by mttwc** [comment]
I'm wondering if we can get rid of all the mock implementations entirely and replace them with sinon mocks and have the same (or even better) level of testability.

**Comment by VishaalK** [comment]
^ I think this is the correct approach

**Comment by mttwc** [comment]
Resolved in #222 where we centralized the storage wiping in one spot for the frontEnd tests, and use MockStorage injection for extension backend tests.
