### ISSUE TITLE
Re-investigate the use of WebExtensions API to pop up notifications from the extension icon itself

### ISSUE THREAD

**Issue by mttwc** [OneNoteDev/WebClipper#48]
Currently, it could be argued that our pageNav style popups break user workflow and some users reported to be annoyed by it. I think this is a good opportunity to re-explore WebExtensions API for notifications and see if we can come up with a better experience.

**Comment by larsendaniel** [comment]
Agreed, I think that is a great idea!

**Comment by mttwc** [comment]
Closing this. We tried this, but the changes to the WebExtensions permissions make it not worth it.
