### ISSUE TITLE
WYSIWYG for Preview is unusual on pages that use new HTML5 tags

### ISSUE THREAD

**Issue by VishaalK** [OneNoteDev/WebClipper#60]
The W3C Specification links on http://html5doctor.com/the-figure-figcaption-elements/ show up large and indented in the prod preview, but are tiny in the actual OneNote page. 

OneNote converts unknown tags to divs and so the styling in the preview is hard to get correct.

**Comment by mttwc** [comment]
@VishaalK you have recently merged in a change that involves sanitizing html (https://github.com/OneNoteDev/WebClipper/pull/66). Was this resolved in your PR by any chance?

EDIT: Looks like there's still some minor differences. Hyperlinks don't look the same in OneNote.
