### ISSUE TITLE
FullPageScreenshotCall has a tendency to time out on larger sites with lots of images

### ISSUE THREAD

**Issue by mttwc** [OneNoteDev/WebClipper#68]
Example: http://html5doctor.com/the-figure-figcaption-elements/
For me, this is hitting the 30s timeout consistently.

**Comment by iconix** [comment]
Might be nice to get some data to back this up... how often is this happening for users? Our weekly averages hover between 9-11 seconds.

![image](https://cloud.githubusercontent.com/assets/1144401/19004884/d3c36636-870c-11e6-8885-58007c0e24ac.png)

Also, how many users are going to be willing to wait longer than 30s for a preview to show up anyway? I would think that most likely, users will just clip without waiting for the full timeout...
