### ISSUE TITLE
PDF Mode on Firefox Clipper is returning extra images and incorrectly shows a result for Augmentation Mode when it shouldn't

### ISSUE THREAD

**Issue by VishaalK** [OneNoteDev/WebClipper#75]
I repro'd it on the current dev build and on the build in "production", 3.2.4

http://www.pdf995.com/samples/pdf.pdf

^ Compare the Chrome Clipper on this page to the Firefox one. There are two extra images and the article mode has text, when it should say "No content found".

**Comment by mttwc** [comment]
@VishaalK I think you mentioned that you found the root cause for this, is this resolved?

**Comment by mttwc** [comment]
Fixed with PDF mode v1 when it became its own mode and disabling augmentation and fullpage mode.

https://github.com/OneNoteDev/WebClipper/pull/146
