### ISSUE TITLE
Authentication errors need to be bubbled up to the user

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/WebClipper#85]
When the authentication service hits an error, it is generally returned as part of the redirect URL.  We are currently logging this error, but really it should be something that we can bubble up to the user.  This is mostly because most of the time we don't have any control over it and the error is specific to that user.

This is tracking the work to somehow bubble up the error message we get back to the user.

Current (initial) thoughts are to add a "more info" link which opens up a popup with the message (as well as the clipper ID/session ID to help debug.

**Comment by mttwc** [comment]
Note that we know get this on the client, however we still need to display it to the user in the 'right way'.
