### ISSUE TITLE
Choice Hotels web page renders a blank image in Full Page Screenshot

### ISSUE THREAD

**Issue by VishaalK** [OneNoteDev/WebClipper#9]
1. Navigate to https://www.choicehotels.com/mississippi/hattiesburg/clarion-hotels/ms140?sid=xGvANg.IuZC3g1Uu.32
2. Open Clipper in Full Page Mode

**Expected:** Screenshot of the page
**Actual;** Blank Image

More broken links:
https://mqshen.gitbooks.io/prml/content/Chapter2/gaussian/sequential_estimation.html

**Comment by mttwc** [comment]
It looks like the HERE Maps is being picked up as a giant gray block, and everything around it is being ignored. A decent starting step would be to check that we're sending our API the right html.
